routes/web.php
<?php

use App\Http\Controllers\ApiInstagramController;
use App\Http\Controllers\PostController;
use App\Http\Controllers\BookController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\CkeditorController;
use App\Http\Controllers\ClientController;
use App\Http\Controllers\ClientSaysController;
use App\Http\Controllers\ClinicalApplicationController;
use App\Http\Controllers\CountController;
use App\Http\Controllers\DemoController;
use App\Http\Controllers\DiscusUsController;
use App\Http\Controllers\GalleryController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\PhotoProductController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\RequestBookListController;
use App\Http\Controllers\SliderContactUsController;
use App\Http\Controllers\SliderController;
use App\Http\Controllers\SliderProductController;
use App\Http\Controllers\SubscribeController;
use App\Http\Controllers\TagController;
use App\Http\Controllers\TeamController;
use App\Http\Controllers\TestimonyController;
use App\Http\Controllers\YoutubeController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', function () {
    return redirect()->route('login');
});



Auth::routes([
    'register' => false, // Registration Routes...
    'reset' => false, // Password Reset Routes...
    'verify' => false, // Email Verification Routes...  
]);
Route::middleware(['auth'])->group(function () {
    Route::resource('/posts', PostController::class);
    Route::get('/home', [HomeController::class, 'index'])->name('home');
    Route::resource('slider', SliderController::class);
    Route::resource('slider-contact-us', SliderContactUsController::class);
    Route::resource('slider-product', SliderProductController::class);
    Route::resource('booking-demo',DemoController::class);
    Route::get('booking-demo-download',[DemoController::class,'export'])->name('booking.export');
    Route::get('discus-download',[DiscusUsController::class,'export'])->name('discus.export');
    Route::get('subscribe-download',[SubscribeController::class,'export'])->name('subscribe.export');
    Route::resource('client',ClientController::class);
    Route::resource('testimoni',TestimonyController::class);
    Route::resource('team',TeamController::class);
    Route::resource('gallery',GalleryController::class);
    Route::resource('book',BookController::class);
    Route::resource('categories',CategoryController::class);
    Route::resource('tag',TagController::class);
    Route::put('/posts/{post}/publish', [PostController::class,'publish'])->name('posts.publish');
    Route::post('ckeditor/image_upload', [CkeditorController::class, 'upload'])->name('posts.upload');
    Route::get('/subscribe',[SubscribeController::class,'index'])->name('subscribe.index');
    Route::get('/discus',[DiscusUsController::class,'index'])->name('discus.index');
    Route::get('/product/{id}',[ProductController::class,'index'])->name('product.menu');
    Route::resource('photo-product',PhotoProductController::class);
    route::get('/clinical-application/{product_id}',[ClinicalApplicationController::class,'index'])->name('clinical_application.index');
    route::get('/clinical-application-detail/{product_id}/{id}',[ClinicalApplicationController::class,'detail'])->name('clinical_application.detail');
    route::get('/clinical-application-edit/{product_id}/{id}/{detail_id}',[ClinicalApplicationController::class,'edit'])->name('clinical_application.edit');
    route::put('/clinical-application-edit/{product_id}/{id}/{detail_id}',[ClinicalApplicationController::class,'update'])->name('clinical_application.put');
    Route::get('/youtube',[YoutubeController::class,'index'])->name('youtube.index');
    Route::put('/youtube',[YoutubeController::class,'update'])->name('youtube.update');
    Route::get('/request-buku',[RequestBookListController::class,'list'])->name('req-buku.index');
    Route::get('/request-buku-export',[RequestBookListController::class,'export'])->name('req-buku.export');
    Route::resource('client-says',ClientSaysController::class);
    
});

Route::get('/visitor', [CountController::class,'grafik'])->name('visitor-api');

app/Models/Book.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Book extends Model
{
    use HasFactory;
    protected $fillable = ['judul', 'link','cover'];
}

app/Http/Controllers/BookController.php
<?php

namespace App\Http\Controllers;

use App\Helpers\ResponseHelper;
use App\Http\Requests\BookPostRequest;
use App\Models\Book;
use Illuminate\Http\Request;

class BookController extends Controller
{
     /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $book = Book::orderBy('created_at', 'desc')->paginate(10);
        return view('dashboard.book.book', compact('book'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('dashboard.book.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(BookPostRequest $request)
    {
        
        $file = $request->file('cover');
        $tujuan_upload = public_path('upload/book');
        $fileNameBook = time().'.'.$file->extension();  
        $file->move($tujuan_upload, $fileNameBook);


        $file = $request->file('link');
        $tujuan_upload = public_path('upload/book-link');
        $fileName = time().'.'.$file->extension();  
        $file->move($tujuan_upload, $fileName);

        Book::create([
            'judul' => $request->judul,
            'link' => asset('upload/book-link'). "/" . $fileName,
            'cover' => $fileNameBook,
        ]);
        return redirect()->route('book.index')->with('success', 'Sukses Menambahkan book');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $book = Book::find($id);
        return view('dashboard.book.edit', ['book'=>$book]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $slider = Book::find($id);
        if ($request->hasFile('cover')) {
            $file = $request->file('cover');
            $tujuan_upload = public_path('upload/book');
            $fileName = time().'.'.$file->extension();  
            $file->move($tujuan_upload, $fileName);
            $slider->cover = $fileName;
        }

        if ($request->hasFile('link')) {
            $file = $request->file('link');
            $tujuan_upload = public_path('upload/book-link');
            $fileBook = time().'.'.$file->extension();  
            $file->move($tujuan_upload, $fileBook);
            $slider->link = asset('upload/book-link'). "/" . $fileBook;
        }

        $slider->judul=$request->judul;
        $slider->save();
        return redirect()->route('book.index')->with('success', 'Sukses Mengedit book');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $slider = Book::find($id);
        $slider->delete();
        return redirect()->route('book.index')->with('success', 'Sukses Menghapus book');
    }

    public function listBook()
    {
        $slider = Book::orderBy('created_at', 'desc')->get();
        foreach($slider as $s){
            $s->image = asset("upload/book")."/".$s->cover;
        }
        return ResponseHelper::success($slider);
    }
}

resources/views/dashboard/book/book.blade.php
@extends('template.dashboard_template')

@section('content')

<div class="body flex-grow-1 px-3">
    <div class="container-lg">
      <div class="row">
        <div class="col-12">
          <div class="card mb-4">
            <div class="card-header"><strong>Data Buku/Jurnal</strong></div>
            <div class="card-body">
                <a href="{{route('book.create')}}" class="btn btn-primary">Tambah Buku/Jurnal</a>
              <div class="example">
                
                @if (session('success'))
                  <div class="alert alert-success">
                      {{ session('success') }}
                  </div>
              @endif
                <div class="table-responsive">
<table class="table table-hover">
                    <thead>
                      <tr>
                        <th scope="col">No</th>
                        <th scope="col">Judul</th>
                        <th scope="col">Link</th>
                        <th scope="col">Image</th>
                        <th scope="col">Action</th>
                      </tr>
                    </thead>
                    <tbody>
                      @foreach($book as $s)
                        <tr>
                            <td>{{$loop->iteration + $book->firstItem()-1}}</td>
                            <td>{{$s->judul}}</td>
                            <td>{{$s->link}}</td>
                            <td> <img src="{{asset('upload/book/')}}/{{$s->cover}}" style='width:250px;height:auto;' border="0" alt="Null"></td>
                            <td>
                                <a href="{{route('book.edit',$s->id)}}" class="btn btn-success">Edit</a>
                                <form action="{{ route('book.destroy', $s->id) }}" method="POST" onsubmit="return confirm('Are you sure you want to delete this item?')">
                                  @csrf
                                  @method('DELETE')
                                  <button type="submit" class="btn btn-danger">Delete</button>
                              </form>
                            </td>
                        </tr>
                      @endforeach
                    </tbody>
                  </table>
</div>

                  {{ $book->links('vendor.pagination.bootstrap-4') }}


              </div>
            </div>
          </div>
        </div>

      </div>
    </div>
  </div>

@endsection

resources/views/dashboard/book/create.blade.php
@extends('template.dashboard_template')

@section('content')

<div class="body flex-grow-1 px-3">
    <div class="container-lg">
        <div class="row">
            <div class="col-12">
                <div class="card mb-4">
                    <div class="card-header"><strong>Tambah Buku</strong></div>
                    <div class="card-body">
                        <div class="example">
                            <form method="POST" action="{{route('book.store')}}" enctype='multipart/form-data'>
                                @if(count($errors) > 0)
                                <div class="alert alert-danger">
                                    @foreach ($errors->all() as $error)
                                    {{ $error }} <br/>
                                    @endforeach
                                </div>
                                @endif
                
                                @csrf
                                <div class="form-floating mb-3">
                                    <input type="text" class="form-control" name="judul" id="floatingInput" placeholder="Judul" >
                                    <label for="floatingInput">Judul</label>
                                </div>
                                
                                <div class="mt-2">
                                    <label for="book" class="form-label">Upload Buku</label>
                                    <input type="file" class="form-control" id="book" name="link" required accept=".doc,.docx,.pdf">
                                </div>
                                
                                <div class="mt-2">
                                    <label for="exampleInputPassword1" class="form-label">Cover</label>
                                    <input type="file" id="cover" class="form-control" id="exampleInputPassword1" name="cover" required>
                                  </div>
                                  <div class="mt-2">
                                    <button type="submit" class="btn btn-primary">Submit</button>
                                  </div>
                                

                            </form>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>

@endsection

resources/views/dashboard/book/edit.blade.php
@extends('template.dashboard_template')

@section('content')

<div class="body flex-grow-1 px-3">
    <div class="container-lg">
        <div class="row">
            <div class="col-12">
                <div class="card mb-4">
                    <div class="card-header"><strong>Edit Buku</strong></div>
                    <div class="card-body">
                        <div class="example">
                            <form method="POST" action="{{route('book.update',$book->id)}}" enctype='multipart/form-data'>
                               
                                @if(count($errors) > 0)
                                <div class="alert alert-danger">
                                    @foreach ($errors->all() as $error)
                                    {{ $error }} <br/>
                                    @endforeach
                                </div>
                                @endif
                
                                @csrf
                                @method("PUT")
                                <div class="form-floating mb-3">
                                    <input type="text" class="form-control" name="judul" id="floatingInput" placeholder="Judul" value="{{$book->judul}}">
                                    <label for="floatingInput">Judul</label>
                                </div>
                                
                                <div class="mt-2">
                                    <label for="upload-book" class="form-label">Upload Buku</label>
                                    <input type="file" class="form-control" id="upload-book" name="link"  accept=".doc,.docx,.pdf">
                                </div>
                                
                                <div class="mt-2">
                                    <label for="exampleInputPassword1" class="form-label">Download Buku</label>
                                    <p><a href="{{$book->link}}">Download Link Sekarang</a></p>
                                </div>
                                
                                <div class="mt-2">
                                    <label for="floatingPassword">Cover Sekarang</label>
                                    <br>
                                    <img id="image-preview"  src="{{asset('upload/book/')}}/{{$book->cover}}" style='width:250px;height:auto;' border="0" alt="Null">
                                </div>
                                <div class="mt-2">
                                    <label for="exampleInputPassword1" class="form-label">Ganti Cover</label>
                                    <input type="file" id="cover" class="form-control" id="exampleInputPassword1" name="cover" >
                                  </div>

                                  <div class="mt-2">
                                    <button type="submit" class="btn btn-primary">Submit</button>
                                  </div>
                                

                            </form>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>
@push('custom-scripts')
<script>
$(document).ready(function() {
    // Ketika pengguna memilih file baru
    $('#cover').change(function() {
      if (this.files && this.files[0]) {
        var reader = new FileReader();
        reader.onload = function(e) {
          // Mengubah atribut 'src' pada elemen gambar untuk menampilkan gambar baru
          $('#image-preview').attr('src', e.target.result);
        }
        // Membaca file yang dipilih oleh pengguna
        reader.readAsDataURL(this.files[0]);
      }
    });
  });
</script>
@endpush

@endsection