routes/web.php
<?php

use App\Http\Controllers\ApiInstagramController;
use App\Http\Controllers\PostController;
use App\Http\Controllers\BookController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\CkeditorController;
use App\Http\Controllers\ClientController;
use App\Http\Controllers\ClientSaysController;
use App\Http\Controllers\ClinicalApplicationController;
use App\Http\Controllers\CountController;
use App\Http\Controllers\DemoController;
use App\Http\Controllers\DiscusUsController;
use App\Http\Controllers\GalleryController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\PhotoProductController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\RequestBookListController;
use App\Http\Controllers\SliderContactUsController;
use App\Http\Controllers\SliderController;
use App\Http\Controllers\SliderProductController;
use App\Http\Controllers\SubscribeController;
use App\Http\Controllers\TagController;
use App\Http\Controllers\TeamController;
use App\Http\Controllers\TestimonyController;
use App\Http\Controllers\YoutubeController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', function () {
    return redirect()->route('login');
});



Auth::routes([
    'register' => false, // Registration Routes...
    'reset' => false, // Password Reset Routes...
    'verify' => false, // Email Verification Routes...  
]);
Route::middleware(['auth'])->group(function () {
    Route::resource('/posts', PostController::class);
    Route::get('/home', [HomeController::class, 'index'])->name('home');
    Route::resource('slider', SliderController::class);
    Route::resource('slider-contact-us', SliderContactUsController::class);
    Route::resource('slider-product', SliderProductController::class);
    Route::resource('booking-demo',DemoController::class);
    Route::get('booking-demo-download',[DemoController::class,'export'])->name('booking.export');
    Route::get('discus-download',[DiscusUsController::class,'export'])->name('discus.export');
    Route::get('subscribe-download',[SubscribeController::class,'export'])->name('subscribe.export');
    Route::resource('client',ClientController::class);
    Route::resource('testimoni',TestimonyController::class);
    Route::resource('team',TeamController::class);
    Route::resource('gallery',GalleryController::class);
    Route::resource('book',BookController::class);
    Route::resource('categories',CategoryController::class);
    Route::resource('tag',TagController::class);
    Route::put('/posts/{post}/publish', [PostController::class,'publish'])->name('posts.publish');
    Route::post('ckeditor/image_upload', [CkeditorController::class, 'upload'])->name('posts.upload');
    Route::get('/subscribe',[SubscribeController::class,'index'])->name('subscribe.index');
    Route::get('/discus',[DiscusUsController::class,'index'])->name('discus.index');
    Route::get('/product/{id}',[ProductController::class,'index'])->name('product.menu');
    Route::resource('photo-product',PhotoProductController::class);
    route::get('/clinical-application/{product_id}',[ClinicalApplicationController::class,'index'])->name('clinical_application.index');
    route::get('/clinical-application-detail/{product_id}/{id}',[ClinicalApplicationController::class,'detail'])->name('clinical_application.detail');
    route::get('/clinical-application-edit/{product_id}/{id}/{detail_id}',[ClinicalApplicationController::class,'edit'])->name('clinical_application.edit');
    route::put('/clinical-application-edit/{product_id}/{id}/{detail_id}',[ClinicalApplicationController::class,'update'])->name('clinical_application.put');
    Route::get('/youtube',[YoutubeController::class,'index'])->name('youtube.index');
    Route::put('/youtube',[YoutubeController::class,'update'])->name('youtube.update');
    Route::get('/request-buku',[RequestBookListController::class,'list'])->name('req-buku.index');
    Route::get('/request-buku-export',[RequestBookListController::class,'export'])->name('req-buku.export');
    Route::resource('client-says',ClientSaysController::class);
    
});

Route::get('/visitor', [CountController::class,'grafik'])->name('visitor-api');

app/Http/Controllers/PhotoProductController.php
<?php

namespace App\Http\Controllers;

use App\Helpers\ResponseHelper;
use App\Http\Requests\PhotoProductRequest;
use App\Models\ProductPhoto;
use Illuminate\Http\Request;

class PhotoProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $id = $request->query('product');
        $photo = ProductPhoto::where('product_name',$id)->orderBy('created_at','desc')->get();
        return view('dashboard.photo_product.index', compact('photo','id'));

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        $id = $request->query('product');
        return view('dashboard.photo_product.create', compact('id'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(PhotoProductRequest $request)
    {
        $file = $request->file('image');
        $tujuan_upload = public_path('upload/photo_product');
        $fileName = time().'.'.$file->extension();  
        $file->move($tujuan_upload, $fileName);
        $id = $request->query('product');
        ProductPhoto::create([
            'image'=>$fileName,
            'product_name'=>$id
        ]);
        return redirect()->route('photo-product.index',['product'=>$id])->with('success', 'Sukses Menambahkan Photo Product');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Request $request, $id)
    {
        $product = $request->query('product');
        $photo = ProductPhoto::find($id);
        return view('dashboard.photo_product.edit', compact('product','photo'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $file = $request->file('image');
        $tujuan_upload = public_path('upload/photo_product');
        $fileName = time().'.'.$file->extension();  
        $file->move($tujuan_upload, $fileName);
        $product = $request->query('product');
        $photo = ProductPhoto::find($id);
        $photo->image = $fileName;
        $photo->save();
        return redirect()->route('photo-product.index',['product'=>$product])->with('success', 'Sukses Mengedit Photo Product');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, $id)
    {
        $product = $request->query('product');
        $photo =ProductPhoto::where('product_name',$product)->where('id',$id)->first();
        $photo->delete();
        
        return redirect()->route('photo-product.index',['product'=>$product])->with('success', 'Sukses Menghapus Photo Product');
    }

    public function listProduct($id)
    {
        $photo =ProductPhoto::where('product_name',$id)->get();
        return ResponseHelper::success($photo);
    }
}

resources/views/dashboard/photo_product/create.blade.php
@extends('template.dashboard_template')

@section('content')

<div class="body flex-grow-1 px-3">
    <div class="container-lg">
        <div class="row">
            <div class="col-12">
                <div class="card mb-4">
                    <div class="card-header"><strong>Tambah Photo Product {{$id}}</strong></div>
                    <div class="card-body">
                        <div class="example">
                            <form method="POST" action="{{route('photo-product.store',['product'=> $id])}}" enctype='multipart/form-data'>
                                @if(count($errors) > 0)
                                <div class="alert alert-danger">
                                    @foreach ($errors->all() as $error)
                                    {{ $error }} <br/>
                                    @endforeach
                                </div>
                                @endif
                
                                @csrf
                                <div class="mt-2">
                                    <label for="exampleInputPassword1" class="form-label">Image</label>
                                    <input type="file" class="form-control" id="exampleInputPassword1" name="image" required>
                                  </div>
                                  <div class="mt-2">
                                    <button type="submit" class="btn btn-primary">Submit</button>
                                  </div>
                                

                            </form>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>

@endsection

resources/views/dashboard/photo_product/edit.blade.php
@extends('template.dashboard_template')

@section('content')

<div class="body flex-grow-1 px-3">
    <div class="container-lg">
        <div class="row">
            <div class="col-12">
                <div class="card mb-4">
                    <div class="card-header"><strong>Edit Photo Product {{$product}}</strong></div>
                    <div class="card-body">
                        <div class="example">
                            <form method="POST" action="{{route('photo-product.update',['photo_product'=>$photo->id, 'product'=>$product])}}" enctype='multipart/form-data'>
                               
                                @if(count($errors) > 0)
                                <div class="alert alert-danger">
                                    @foreach ($errors->all() as $error)
                                    {{ $error }} <br/>
                                    @endforeach
                                </div>
                                @endif
                
                                @csrf
                                @method("PUT")
                               
                                <div class="mt-2">
                                    <label for="floatingPassword">Foto Sekarang</label>
                                    <br>
                                    <img id="image-preview"  src="{{$photo->image}}" style='width:250px;height:auto;' border="0" alt="Null">
                                </div>
                                <div class="mt-2">
                                    <label for="exampleInputPassword1" class="form-label">Ganti Foto</label>
                                    <input type="file" class="form-control" id="exampleInputPassword1" name="image" required>
                                  </div>

                                  <div class="mt-2">
                                    <button type="submit" class="btn btn-primary">Submit</button>
                                  </div>
                                

                            </form>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>
@push('custom-scripts')
<script>
$(document).ready(function() {
    // Ketika pengguna memilih file baru
    $('input[type="file"]').change(function() {
      if (this.files && this.files[0]) {
        var reader = new FileReader();
        reader.onload = function(e) {
          // Mengubah atribut 'src' pada elemen gambar untuk menampilkan gambar baru
          $('#image-preview').attr('src', e.target.result);
        }
        // Membaca file yang dipilih oleh pengguna
        reader.readAsDataURL(this.files[0]);
      }
    });
  });
</script>
@endpush

@endsection

resources/views/dashboard/photo_product/index.blade.php
@extends('template.dashboard_template')

@section('content')
@php
use Illuminate\Support\Str;
@endphp

<div class="body flex-grow-1 px-3">
    <div class="container-lg">
        <div class="row">
            <div class="col-12">
                <div class="card mb-4">
                    <div class="card-header"><strong>List Photo Product {{$id}}</strong>
                        <nav style="--cui-breadcrumb-divider: '>';" aria-label="breadcrumb">
                            <ol class="breadcrumb">
                              <li class="breadcrumb-item"><a href="{{route('product.menu',['id'=>$id])}}">{{$id}}</a></li>
                              <li class="breadcrumb-item active" aria-current="page">Photo Product</li>
                            </ol>
                          </nav>
                    </div>
                    <div class="card-body">
                        <div class="panel-heading">
                            <h2>
                                Photo
        
                                <a href="{{ route('photo-product.create',['product'=>$id]) }}" class="btn btn-primary pull-right">Buat Baru</a>
                            </h2>
                        </div>
                        <div class="example">
                            <div class="panel-body">
                                <table class="table">
                                    <thead>
                                        <tr>
                                            <th>No</th>
                                            <th>Photo</th>
                                            <th>Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @forelse ($photo as $p)
                                        <tr>
                                            <td> {{$loop->iteration}} </td>
                                            <td>
                                            <img src="{{$p->image}}" style='width:250px;height:auto;' border="0" alt="Null">
                                            </td>
                                            <td>
                                                <a href="{{route('photo-product.edit', ['photo_product' => $p->id, 'product' => $id])}}" class="btn btn-success">Edit</a>
                                                <form action="{{route('photo-product.destroy', ['photo_product' => $p->id, 'product' => $id])}}" method="POST" onsubmit="return confirm('Are you sure you want to delete this item?')">
                                                  @csrf
                                                  @method('DELETE')
                                                  <button type="submit" class="btn btn-danger">Delete</button>
                                              </form>
                                            </td>
                                        </tr>
                                        @empty
                                        <tr>
                                            <td colspan="5">No Photo available.</td>
                                        </tr>
                                        @endforelse
                                    </tbody>
                                </table>
</div>

                            
            
                            </div>
                        </div>
                    </div>
                  </div>
            </div>
        </div>
    </div>
</div>
   
@endsection