routes/web.php
<?php

use App\Http\Controllers\ApiInstagramController;
use App\Http\Controllers\PostController;
use App\Http\Controllers\BookController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\CkeditorController;
use App\Http\Controllers\ClientController;
use App\Http\Controllers\ClientSaysController;
use App\Http\Controllers\ClinicalApplicationController;
use App\Http\Controllers\CountController;
use App\Http\Controllers\DemoController;
use App\Http\Controllers\DiscusUsController;
use App\Http\Controllers\GalleryController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\PhotoProductController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\RequestBookListController;
use App\Http\Controllers\SliderContactUsController;
use App\Http\Controllers\SliderController;
use App\Http\Controllers\SliderProductController;
use App\Http\Controllers\SubscribeController;
use App\Http\Controllers\TagController;
use App\Http\Controllers\TeamController;
use App\Http\Controllers\TestimonyController;
use App\Http\Controllers\YoutubeController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', function () {
    return redirect()->route('login');
});



Auth::routes([
    'register' => false, // Registration Routes...
    'reset' => false, // Password Reset Routes...
    'verify' => false, // Email Verification Routes...  
]);
Route::middleware(['auth'])->group(function () {
    Route::resource('/posts', PostController::class);
    Route::get('/home', [HomeController::class, 'index'])->name('home');
    Route::resource('slider', SliderController::class);
    Route::resource('slider-contact-us', SliderContactUsController::class);
    Route::resource('slider-product', SliderProductController::class);
    Route::resource('booking-demo',DemoController::class);
    Route::get('booking-demo-download',[DemoController::class,'export'])->name('booking.export');
    Route::get('discus-download',[DiscusUsController::class,'export'])->name('discus.export');
    Route::get('subscribe-download',[SubscribeController::class,'export'])->name('subscribe.export');
    Route::resource('client',ClientController::class);
    Route::resource('testimoni',TestimonyController::class);
    Route::resource('team',TeamController::class);
    Route::resource('gallery',GalleryController::class);
    Route::resource('book',BookController::class);
    Route::resource('categories',CategoryController::class);
    Route::resource('tag',TagController::class);
    Route::put('/posts/{post}/publish', [PostController::class,'publish'])->name('posts.publish');
    Route::post('ckeditor/image_upload', [CkeditorController::class, 'upload'])->name('posts.upload');
    Route::get('/subscribe',[SubscribeController::class,'index'])->name('subscribe.index');
    Route::get('/discus',[DiscusUsController::class,'index'])->name('discus.index');
    Route::get('/product/{id}',[ProductController::class,'index'])->name('product.menu');
    Route::resource('photo-product',PhotoProductController::class);
    route::get('/clinical-application/{product_id}',[ClinicalApplicationController::class,'index'])->name('clinical_application.index');
    route::get('/clinical-application-detail/{product_id}/{id}',[ClinicalApplicationController::class,'detail'])->name('clinical_application.detail');
    route::get('/clinical-application-edit/{product_id}/{id}/{detail_id}',[ClinicalApplicationController::class,'edit'])->name('clinical_application.edit');
    route::put('/clinical-application-edit/{product_id}/{id}/{detail_id}',[ClinicalApplicationController::class,'update'])->name('clinical_application.put');
    Route::get('/youtube',[YoutubeController::class,'index'])->name('youtube.index');
    Route::put('/youtube',[YoutubeController::class,'update'])->name('youtube.update');
    Route::get('/request-buku',[RequestBookListController::class,'list'])->name('req-buku.index');
    Route::get('/request-buku-export',[RequestBookListController::class,'export'])->name('req-buku.export');
    Route::resource('client-says',ClientSaysController::class);
    
});

Route::get('/visitor', [CountController::class,'grafik'])->name('visitor-api');

resources/views/dashboard/banner_contact_us/create.blade.php
@extends('template.dashboard_template')

@section('content')

<div class="body flex-grow-1 px-3">
    <div class="container-lg">
        <div class="row">
            <div class="col-12">
                <div class="card mb-4">
                    <div class="card-header"><strong>Tambah Slider</strong></div>
                    <div class="card-body">
                        <div class="example">
                            <form method="POST" action="{{route('slider.store')}}" enctype='multipart/form-data'>
                                @if(count($errors) > 0)
                                <div class="alert alert-danger">
                                    @foreach ($errors->all() as $error)
                                    {{ $error }} <br/>
                                    @endforeach
                                </div>
                                @endif
                
                                @csrf
                                <div class="form-floating mb-3">
                                    <input type="text" class="form-control" name="title" id="floatingInput" placeholder="Title">
                                    <label for="floatingInput">Title</label>
                                </div>
                                <div class="form-floating mb-3">
                                    <select class="form-select" name="type" id="type" aria-label="type">
                                        <option selected>Type</option>
                                        <option value="home">Home</option>
                                        <option value="product">Product</option>
                                        <option value="news">News</option>
                                      </select>
                                </div>
                                <div class="form-floating mb-3">
                                    <input type="text" class="form-control" id="floatingSubtitle"
                                        placeholder="Sub Title" name="subtitle">
                                    <label for="floatingSubtitle" id="subtitle">Subtitle</label>
                                </div>
                                
                                <div class="mt-2">
                                    <label for="exampleInputPassword1" class="form-label">Image</label>
                                    <input type="file" class="form-control" id="exampleInputPassword1" name="image" required>
                                  </div>
                                  <div class="mt-2">
                                    <button type="submit" class="btn btn-primary">Submit</button>
                                  </div>
                                

                            </form>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>

@push('custom-scripts')
<script>
$(document).ready(function() {
    $('#type').on('change', function() {
        if ($(this).val() === 'product') {
            // Jika tipe yang dipilih adalah 'product'
            $('input[name="subtitle"]').hide(); // Sembunyikan input sub title
            $("#subtitle").hide();
        } else {
            $('input[name="subtitle"]').show(); // Tampilkan input sub title untuk tipe lainnya
            $("#subtitle").show();
        }
    });
});
</script>
@endpush



@endsection

resources/views/dashboard/banner_contact_us/edit.blade.php
@extends('template.dashboard_template')

@section('content')

<div class="body flex-grow-1 px-3">
    <div class="container-lg">
        <div class="row">
            <div class="col-12">
                <div class="card mb-4">
                    <div class="card-header"><strong>Edit Slider</strong></div>
                    <div class="card-body">
                        <div class="example">
                            <form method="POST" action="{{route('slider-contact-us.update',$slider->id)}}" enctype='multipart/form-data'>
                               
                                @if(count($errors) > 0)
                                <div class="alert alert-danger">
                                    @foreach ($errors->all() as $error)
                                    {{ $error }} <br/>
                                    @endforeach
                                </div>
                                @endif
                
                                @csrf
                                @method("PUT")
                                <div class="form-floating mb-3">
                                    <input type="text" class="form-control" name="title" id="floatingInput" placeholder="Title" value="{{$slider->title}}">
                                    <label for="floatingInput">Title</label>
                                </div>
                              

                               

                                <div class="form-floating mb-3">
                                    <input type="text" class="form-control" id="floatingPassword"
                                        placeholder="Sub Title" name="subtitle" value="{{$slider->subtitle}}">
                                    <label for="floatingPassword" id="subtitle">Sub Title</label>
                                </div>
                              
                                <div class="mt-2">
                                    <label for="floatingPassword">Foto Sekarang</label>
                                    <br>
                                    <img id="image-preview"  src="{{asset('upload/slider-contact/')}}/{{$slider->image}}" style='width:250px;height:auto;' border="0" alt="Null">
                                </div>
                                <div class="mt-2">
                                    <label for="exampleInputPassword1" class="form-label">Ganti Foto</label>
                                    <input type="file" class="form-control" id="exampleInputPassword1" name="image" >
                                  </div>

                                  <div class="mt-2">
                                    <button type="submit" class="btn btn-primary">Submit</button>
                                  </div>
                                

                            </form>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>
@push('custom-scripts')
<script>
$(document).ready(function() {
    // Ketika pengguna memilih file baru
    $('input[type="file"]').change(function() {
      if (this.files && this.files[0]) {
        var reader = new FileReader();
        reader.onload = function(e) {
          // Mengubah atribut 'src' pada elemen gambar untuk menampilkan gambar baru
          $('#image-preview').attr('src', e.target.result);
        }
        // Membaca file yang dipilih oleh pengguna
        reader.readAsDataURL(this.files[0]);
      }
    });
  });

  $(document).ready(function() {
    $('#type').on('change', function() {
        if ($(this).val() === 'product') {
            // Jika tipe yang dipilih adalah 'product'
            $('input[name="subtitle"]').hide(); // Sembunyikan input sub title
            $("#subtitle").hide();
        } else {
            $('input[name="subtitle"]').show(); // Tampilkan input sub title untuk tipe lainnya
            $("#subtitle").show();
        }
    });
});
</script>
@endpush

@endsection

resources/views/dashboard/banner_contact_us/slider.blade.php
@extends('template.dashboard_template')

@section('content')

<div class="body flex-grow-1 px-3">
    <div class="container-lg">
      <div class="row">
        <div class="col-12">
          <div class="card mb-4">
            <div class="card-header"><strong>Data Slider</strong></div>
            <div class="card-body">
                {{-- <a href="{{route('slider.create')}}" class="btn btn-primary">Tambah Slider</a> --}}
              <div class="example">
                
                @if (session('success'))
                  <div class="alert alert-success">
                      {{ session('success') }}
                  </div>
              @endif
                <div class="table-responsive">
<table class="table table-hover">
                    <thead>
                      <tr>
                        <th scope="col">No</th>
                        <th scope="col">Title</th>
                        <th scope="col">Sub Title</th>
                        <th scope="col">Image</th>
                        <th scope="col">Action</th>
                      </tr>
                    </thead>
                    <tbody>
                      @foreach($slider as $s)
                     =
                        <tr>
                            <td>{{$loop->iteration + $slider->firstItem()-1}}</td>
                            <td>{{$s->title}}</td>
                            <td>{{$s->subtitle}}</td>
                            
                            <td> <img src="{{asset('upload/slider-contact/')}}/{{$s->image}}" style='width:250px;height:auto;' border="0" alt="Null"></td>
                            <td>
                                <a href="{{route('slider-contact-us.edit',$s->id)}}" class="btn btn-success">Edit</a>
                                {{-- <form action="{{ route('slider.destroy', $s->id) }}" method="POST" onsubmit="return confirm('Are you sure you want to delete this item?')">
                                  @csrf
                                  @method('DELETE')
                                  <button type="submit" class="btn btn-danger">Delete</button>
                              </form> --}}
                            </td>
                        </tr>
                      @endforeach
                    </tbody>
                  </table>
</div>

                  {{ $slider->links('vendor.pagination.bootstrap-4') }}


              </div>
            </div>
          </div>
        </div>

      </div>
    </div>
  </div>

@endsection