routes/web.php
<?php

use App\Http\Controllers\ApiInstagramController;
use App\Http\Controllers\PostController;
use App\Http\Controllers\BookController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\CkeditorController;
use App\Http\Controllers\ClientController;
use App\Http\Controllers\ClientSaysController;
use App\Http\Controllers\ClinicalApplicationController;
use App\Http\Controllers\CountController;
use App\Http\Controllers\DemoController;
use App\Http\Controllers\DiscusUsController;
use App\Http\Controllers\GalleryController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\PhotoProductController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\RequestBookListController;
use App\Http\Controllers\SliderContactUsController;
use App\Http\Controllers\SliderController;
use App\Http\Controllers\SliderProductController;
use App\Http\Controllers\SubscribeController;
use App\Http\Controllers\TagController;
use App\Http\Controllers\TeamController;
use App\Http\Controllers\TestimonyController;
use App\Http\Controllers\YoutubeController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', function () {
    return redirect()->route('login');
});



Auth::routes([
    'register' => false, // Registration Routes...
    'reset' => false, // Password Reset Routes...
    'verify' => false, // Email Verification Routes...  
]);
Route::middleware(['auth'])->group(function () {
    Route::resource('/posts', PostController::class);
    Route::get('/home', [HomeController::class, 'index'])->name('home');
    Route::resource('slider', SliderController::class);
    Route::resource('slider-contact-us', SliderContactUsController::class);
    Route::resource('slider-product', SliderProductController::class);
    Route::resource('booking-demo',DemoController::class);
    Route::get('booking-demo-download',[DemoController::class,'export'])->name('booking.export');
    Route::get('discus-download',[DiscusUsController::class,'export'])->name('discus.export');
    Route::get('subscribe-download',[SubscribeController::class,'export'])->name('subscribe.export');
    Route::resource('client',ClientController::class);
    Route::resource('testimoni',TestimonyController::class);
    Route::resource('team',TeamController::class);
    Route::resource('gallery',GalleryController::class);
    Route::resource('book',BookController::class);
    Route::resource('categories',CategoryController::class);
    Route::resource('tag',TagController::class);
    Route::put('/posts/{post}/publish', [PostController::class,'publish'])->name('posts.publish');
    Route::post('ckeditor/image_upload', [CkeditorController::class, 'upload'])->name('posts.upload');
    Route::get('/subscribe',[SubscribeController::class,'index'])->name('subscribe.index');
    Route::get('/discus',[DiscusUsController::class,'index'])->name('discus.index');
    Route::get('/product/{id}',[ProductController::class,'index'])->name('product.menu');
    Route::resource('photo-product',PhotoProductController::class);
    route::get('/clinical-application/{product_id}',[ClinicalApplicationController::class,'index'])->name('clinical_application.index');
    route::get('/clinical-application-detail/{product_id}/{id}',[ClinicalApplicationController::class,'detail'])->name('clinical_application.detail');
    route::get('/clinical-application-edit/{product_id}/{id}/{detail_id}',[ClinicalApplicationController::class,'edit'])->name('clinical_application.edit');
    route::put('/clinical-application-edit/{product_id}/{id}/{detail_id}',[ClinicalApplicationController::class,'update'])->name('clinical_application.put');
    Route::get('/youtube',[YoutubeController::class,'index'])->name('youtube.index');
    Route::put('/youtube',[YoutubeController::class,'update'])->name('youtube.update');
    Route::get('/request-buku',[RequestBookListController::class,'list'])->name('req-buku.index');
    Route::get('/request-buku-export',[RequestBookListController::class,'export'])->name('req-buku.export');
    Route::resource('client-says',ClientSaysController::class);
    
});

Route::get('/visitor', [CountController::class,'grafik'])->name('visitor-api');

app/Models/Category.php
<?php

namespace App\Models;

use App\Models\Post;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use HasFactory;

    protected $fillable = ['name'];

    protected static function boot()
    {
        parent::boot();
        static::deleting(function ($category) {
            $category->posts()->delete();
        });
    }

    public function posts()
    {
        return $this->hasMany(Post::class);
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Helpers\ResponseHelper;
use App\Models\Category;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
 public function index()
{
    $categories = Category::orderBy('created_at','desc')->paginate(10);
    return view('dashboard.categories.index', compact('categories'));
}

public function create()
{
    return view('dashboard.categories.create');
}

public function store(Request $request)
{
    $request->validate([
        'name' => 'required'
    ]);

    Category::create($request->all());

    return redirect()->route('categories.index')
        ->with('success', 'Category created successfully.');
}

public function show(Category $category)
{
    // return view('categories.show', compact('category'));
}

public function edit(Category $category)
{
    return view('dashboard.categories.edit', compact('category'));
}

public function update(Request $request, Category $category)
{
    $request->validate([
        'name' => 'required'
    ]);

    $category->update($request->all());

    return redirect()->route('categories.index')
        ->with('success', 'Category updated successfully.');
}

public function destroy(Category $category)
{
    $category->delete();

    return redirect()->route('categories.index')
        ->with('success', 'Category deleted successfully.');
}
public function list()
{
    $categories = Category::orderBy('created_at','desc')->paginate();
    return ResponseHelper::success($categories);
}
}

resources/views/dashboard/categories/create.blade.php
@extends('template.dashboard_template')

@section('content')

<div class="body flex-grow-1 px-3">
    <div class="container-lg">
        <div class="row">
            <div class="col-12">
                <div class="card mb-4">
                    <div class="card-header"><strong>Tambah Category</strong></div>
                    <div class="card-body">
                        <div class="example">
                            <form method="POST" action="{{route('categories.store')}}" enctype='multipart/form-data'>
                                @if(count($errors) > 0)
                                <div class="alert alert-danger">
                                    @foreach ($errors->all() as $error)
                                    {{ $error }} <br/>
                                    @endforeach
                                </div>
                                @endif
                
                                @csrf
                                <div class="form-floating mb-3">
                                    <input type="text" class="form-control" name="name" id="floatingInput" placeholder="Title">
                                    <label for="floatingInput">Nama</label>
                                </div>
                               
                                  <div class="mt-2">
                                    <button type="submit" class="btn btn-primary">Submit</button>
                                  </div>
                                

                            </form>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>

@endsection

resources/views/dashboard/categories/edit.blade.php
@extends('template.dashboard_template')

@section('content')

<div class="body flex-grow-1 px-3">
    <div class="container-lg">
        <div class="row">
            <div class="col-12">
                <div class="card mb-4">
                    <div class="card-header"><strong>Edit category</strong></div>
                    <div class="card-body">
                        <div class="example">
                            <form method="POST" action="{{route('categories.update',$category->id)}}" enctype='multipart/form-data'>
                               
                                @if(count($errors) > 0)
                                <div class="alert alert-danger">
                                    @foreach ($errors->all() as $error)
                                    {{ $error }} <br/>
                                    @endforeach
                                </div>
                                @endif
                
                                @csrf
                                @method("PUT")
                                <div class="form-floating mb-3">
                                    <input type="text" class="form-control" name="name" id="floatingInput" placeholder="Title" value="{{$category->name}}">
                                    <label for="floatingInput">Nama category</label>
                                </div>
                              
                              
                               

                                  <div class="mt-2">
                                    <button type="submit" class="btn btn-primary">Submit</button>
                                  </div>
                                

                            </form>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>


@endsection

resources/views/dashboard/categories/index.blade.php
@extends('template.dashboard_template')

@section('content')

<div class="body flex-grow-1 px-3">
    <div class="container-lg">
      <div class="row">
        <div class="col-12">
          <div class="card mb-4">
            <div class="card-header"><strong>Data Category</strong></div>
            <div class="card-body">
                <a href="{{route('categories.create')}}" class="btn btn-primary">Tambah Category</a>
              <div class="example">
                
                @if (session('success'))
                  <div class="alert alert-success">
                      {{ session('success') }}
                  </div>
              @endif
                <div class="table-responsive">
<table class="table table-hover">
                    <thead>
                      <tr>
                        <th scope="col">No</th>
                        <th scope="col">Nama</th>
                        <th scope="col">Action</th>
                      </tr>
                    </thead>
                    <tbody>
                      @foreach($categories as $s)
                        <tr>
                            <td>{{$loop->iteration + $categories->firstItem()-1}}</td>
                            <td>{{$s->name}}</td>
                            <td>
                                <a href="{{route('categories.edit',$s->id)}}" class="btn btn-success">Edit</a>
                                <form action="{{ route('categories.destroy', $s->id) }}" method="POST" onsubmit="return confirm('Are you sure you want to delete this item?')">
                                  @csrf
                                  @method('DELETE')
                                  <button type="submit" class="btn btn-danger">Delete</button>
                              </form>
                            </td>
                        </tr>
                      @endforeach
                    </tbody>
                  </table>
</div>

                  {{ $categories->links('vendor.pagination.bootstrap-4') }}


              </div>
            </div>
          </div>
        </div>

      </div>
    </div>
  </div>

@endsection